apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config-cliente2
data:
  odoo.conf: |
    [options]
    addons_path = /mnt/enterprise-addons,/usr/lib/python3/dist-packages/odoo/addons
    db_host = 10.112.0.3
    db_port = 5432
    db_user = odoo
    db_password = Cloudlion2026!
    db_name = cliente2_db
    list_db = False
    proxy_mode = True
    admin_passwd = admin_password_segura_2
    limit_time_real = 1200
    workers = 0