apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-filestore-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /odoo_data
    server: 10.100.208.34
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: odoo-filestore-pv
  resources:
    requests:
      storage: 1Ti
